syntax = "proto3";
import "google/protobuf/descriptor.proto";
import "schema/schema.proto";

package test.relations;
option go_package = "test/relations";


message Output {
  repeated Entity entities = 1;
}


message Entity {

  oneof entity {
    Customer customer = 1;
    Order order = 2;
    Item item = 3;
  }
}

message Customer {
  option (schema.table) = { name: "customers" };

  string customer_id = 1 [(schema.field) = { primary_key: true }];
  string name = 2;
}

message Order {
  option (schema.table) = { name: "orders"};

  string order_id = 1 [(schema.field) = {  primary_key: true}];
  string customer_ref_id = 2 [(schema.field) = { foreign_key: "customers on customer_id"}];
  repeated OrderItem items = 3;
}

message OrderItem {
  option (schema.table) = {
    name: "order_items",
    child_of: "orders on order_id"
  };

  // can also leverage orders._id using "order on order_id" if order do not have a external unique identifier
  string item_id = 2 [(schema.field) = { foreign_key: "items on item_id"}];
  int64 quantity = 11;
}

message Item {
  option (schema.table) = { name: "items" };

  string item_id = 1 [(schema.field) = { unique: true }];

  string name = 10;
  double price = 11;
}
