syntax = "proto3";
import "google/protobuf/descriptor.proto";
import "schema/schema.proto";

package test.hm;
option go_package = "test/hm";

message ModuleOutput {
  repeated Transaction transactions = 1;
}

message Entity {
  option (schema.table) = {
    name: "entities"
    many_to_one_relation_field_name: "entity_id"
  };

  oneof Item {
    Payment payment = 1;
    MapCreate map_create = 2;

    Transfer transfers = 10;
    Mint mints = 11;
    Burn burns = 12;

    InitializedAccount initialized_account = 20;
  }
}

message Transaction {
  option (schema.table) = {
    name: "transactions"
    many_to_one_relation_field_name: "transaction_id"
  };

  string trx_hash = 1;
  repeated Entity entities = 2;
}


message Payment {
  option (schema.table) = {name: "payment"};
  Mint mint = 1;
  PaymentType type = 2;
}

enum PaymentType {
  UNSET = 0;
  MINT = 1;
  REGULAR_DRIVER = 2;
  NO_SPLIT = 3;
  AI_TRAINER = 4;
  OPERATIONAL = 5;
  REWARD = 6;
  FLEET_MANAGER = 7;
  FLEET_DRIVER = 8;
  MAP_CONSUMPTION = 9;
}

message MapCreate {
  option (schema.table) = {name: "map_create"};

  Burn burn = 1;
}

message Transfer {
  option (schema.table) = {name: "transfer"};

  int64 timestamp = 1;
  string from = 2;
  string to = 3;
  double amount = 4;
}

message Mint {
  option (schema.table) = {name: "mint"};

  int64 timestamp = 1;
  string to = 2;
  double amount = 3;
}

message Burn {
  option (schema.table) = {name: "burn"};

  int64 timestamp = 1;
  string from = 2;
  double amount = 3;
}

message InitializedAccount {
  option (schema.table) = {name: "initialized_account"};
  string account = 1;
  string mint = 2;
  string owner = 3;
}