syntax = "proto3";
import "google/protobuf/descriptor.proto";

package schema;
option go_package = "github.com/streamingfast/substreams-sink-sql/pb/sf/substreams/sink/sql/schema/v1";

extend google.protobuf.MessageOptions {
  Table table = 77701;
}

extend google.protobuf.FieldOptions {
  Column field = 77702;
}

message Table {
  string name = 1;
  optional string child_of = 2;
//  repeated string primary_key_fields = 3;

  optional ClickhouseTableOptions clickhouse_table_options = 200;
}

message Column {
  optional string name = 1;
  optional string foreign_key = 2;
  bool unique = 3;
  bool primary_key = 4;
}

message ClickhouseTableOptions {
    repeated ClickhouseOrderByField order_by_fields = 1;
    repeated ClickhousePartitionByField partition_fields = 2;
    repeated ClickhouseReplacingField replacing_fields = 3;
    repeated ClickhouseIndexField index_fields = 4;
}

message ClickhousePartitionByField {
  string name = 1;
  Function function = 2;
}

message ClickhouseOrderByField {
  string name = 1;
  bool descending = 2;
  Function function = 3;
}

message ClickhouseReplacingField {
  string name = 1;
}

message ClickhouseIndexField {
  string name = 1;
  string field_name = 2;
  IndexType type = 3;
  uint32 granularity = 4;
  Function function = 5;
}

enum IndexType {
  minmax = 0;
  set = 1;
  ngrambf_v1 = 2;
  tokenbf_v1 = 3;
  bloom_filter = 4;
}

enum Function {
  unset = 0;
  toYYYYMM = 1;
  toYYYYDD = 2;
  toYear = 3;
  toMonth = 4;
  toDate = 5;
  toStartOfMonth = 6;
}
