// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: test/hm/hm.proto

package hm

import (
	_ "github.com/streamingfast/substreams-sink-sql/pb/schema"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentType int32

const (
	PaymentType_UNSET           PaymentType = 0
	PaymentType_MINT            PaymentType = 1
	PaymentType_REGULAR_DRIVER  PaymentType = 2
	PaymentType_NO_SPLIT        PaymentType = 3
	PaymentType_AI_TRAINER      PaymentType = 4
	PaymentType_OPERATIONAL     PaymentType = 5
	PaymentType_REWARD          PaymentType = 6
	PaymentType_FLEET_MANAGER   PaymentType = 7
	PaymentType_FLEET_DRIVER    PaymentType = 8
	PaymentType_MAP_CONSUMPTION PaymentType = 9
)

// Enum value maps for PaymentType.
var (
	PaymentType_name = map[int32]string{
		0: "UNSET",
		1: "MINT",
		2: "REGULAR_DRIVER",
		3: "NO_SPLIT",
		4: "AI_TRAINER",
		5: "OPERATIONAL",
		6: "REWARD",
		7: "FLEET_MANAGER",
		8: "FLEET_DRIVER",
		9: "MAP_CONSUMPTION",
	}
	PaymentType_value = map[string]int32{
		"UNSET":           0,
		"MINT":            1,
		"REGULAR_DRIVER":  2,
		"NO_SPLIT":        3,
		"AI_TRAINER":      4,
		"OPERATIONAL":     5,
		"REWARD":          6,
		"FLEET_MANAGER":   7,
		"FLEET_DRIVER":    8,
		"MAP_CONSUMPTION": 9,
	}
)

func (x PaymentType) Enum() *PaymentType {
	p := new(PaymentType)
	*p = x
	return p
}

func (x PaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_test_hm_hm_proto_enumTypes[0].Descriptor()
}

func (PaymentType) Type() protoreflect.EnumType {
	return &file_test_hm_hm_proto_enumTypes[0]
}

func (x PaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentType.Descriptor instead.
func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{0}
}

type ModuleOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *ModuleOutput) Reset() {
	*x = ModuleOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_hm_hm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleOutput) ProtoMessage() {}

func (x *ModuleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_test_hm_hm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleOutput.ProtoReflect.Descriptor instead.
func (*ModuleOutput) Descriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleOutput) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Item:
	//
	//	*Entity_Payment
	//	*Entity_MapCreate
	//	*Entity_Transfers
	//	*Entity_Mints
	//	*Entity_Burns
	//	*Entity_InitializedAccount
	Item isEntity_Item `protobuf_oneof:"Item"`
}

func (x *Entity) Reset() {
	*x = Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_hm_hm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_test_hm_hm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{1}
}

func (m *Entity) GetItem() isEntity_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (x *Entity) GetPayment() *Payment {
	if x, ok := x.GetItem().(*Entity_Payment); ok {
		return x.Payment
	}
	return nil
}

func (x *Entity) GetMapCreate() *MapCreate {
	if x, ok := x.GetItem().(*Entity_MapCreate); ok {
		return x.MapCreate
	}
	return nil
}

func (x *Entity) GetTransfers() *Transfer {
	if x, ok := x.GetItem().(*Entity_Transfers); ok {
		return x.Transfers
	}
	return nil
}

func (x *Entity) GetMints() *Mint {
	if x, ok := x.GetItem().(*Entity_Mints); ok {
		return x.Mints
	}
	return nil
}

func (x *Entity) GetBurns() *Burn {
	if x, ok := x.GetItem().(*Entity_Burns); ok {
		return x.Burns
	}
	return nil
}

func (x *Entity) GetInitializedAccount() *InitializedAccount {
	if x, ok := x.GetItem().(*Entity_InitializedAccount); ok {
		return x.InitializedAccount
	}
	return nil
}

type isEntity_Item interface {
	isEntity_Item()
}

type Entity_Payment struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3,oneof"`
}

type Entity_MapCreate struct {
	MapCreate *MapCreate `protobuf:"bytes,2,opt,name=map_create,json=mapCreate,proto3,oneof"`
}

type Entity_Transfers struct {
	Transfers *Transfer `protobuf:"bytes,10,opt,name=transfers,proto3,oneof"`
}

type Entity_Mints struct {
	Mints *Mint `protobuf:"bytes,11,opt,name=mints,proto3,oneof"`
}

type Entity_Burns struct {
	Burns *Burn `protobuf:"bytes,12,opt,name=burns,proto3,oneof"`
}

type Entity_InitializedAccount struct {
	InitializedAccount *InitializedAccount `protobuf:"bytes,20,opt,name=initialized_account,json=initializedAccount,proto3,oneof"`
}

func (*Entity_Payment) isEntity_Item() {}

func (*Entity_MapCreate) isEntity_Item() {}

func (*Entity_Transfers) isEntity_Item() {}

func (*Entity_Mints) isEntity_Item() {}

func (*Entity_Burns) isEntity_Item() {}

func (*Entity_InitializedAccount) isEntity_Item() {}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrxHash  string    `protobuf:"bytes,1,opt,name=trx_hash,json=trxHash,proto3" json:"trx_hash,omitempty"`
	Entities []*Entity `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_hm_hm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_test_hm_hm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetTrxHash() string {
	if x != nil {
		return x.TrxHash
	}
	return ""
}

func (x *Transaction) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type Payment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mint *Mint       `protobuf:"bytes,1,opt,name=mint,proto3" json:"mint,omitempty"`
	Type PaymentType `protobuf:"varint,2,opt,name=type,proto3,enum=test.hm.PaymentType" json:"type,omitempty"`
}

func (x *Payment) Reset() {
	*x = Payment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_hm_hm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_test_hm_hm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{3}
}

func (x *Payment) GetMint() *Mint {
	if x != nil {
		return x.Mint
	}
	return nil
}

func (x *Payment) GetType() PaymentType {
	if x != nil {
		return x.Type
	}
	return PaymentType_UNSET
}

type MapCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Burn *Burn `protobuf:"bytes,1,opt,name=burn,proto3" json:"burn,omitempty"`
}

func (x *MapCreate) Reset() {
	*x = MapCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_hm_hm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapCreate) ProtoMessage() {}

func (x *MapCreate) ProtoReflect() protoreflect.Message {
	mi := &file_test_hm_hm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapCreate.ProtoReflect.Descriptor instead.
func (*MapCreate) Descriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{4}
}

func (x *MapCreate) GetBurn() *Burn {
	if x != nil {
		return x.Burn
	}
	return nil
}

type Transfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	From      string  `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        string  `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount    float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_hm_hm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_test_hm_hm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{5}
}

func (x *Transfer) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transfer) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transfer) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Mint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	To        string  `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount    float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Mint) Reset() {
	*x = Mint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_hm_hm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mint) ProtoMessage() {}

func (x *Mint) ProtoReflect() protoreflect.Message {
	mi := &file_test_hm_hm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mint.ProtoReflect.Descriptor instead.
func (*Mint) Descriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{6}
}

func (x *Mint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Mint) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Mint) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Burn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	From      string  `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Amount    float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Burn) Reset() {
	*x = Burn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_hm_hm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Burn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Burn) ProtoMessage() {}

func (x *Burn) ProtoReflect() protoreflect.Message {
	mi := &file_test_hm_hm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Burn.ProtoReflect.Descriptor instead.
func (*Burn) Descriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{7}
}

func (x *Burn) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Burn) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Burn) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type InitializedAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Mint    string `protobuf:"bytes,2,opt,name=mint,proto3" json:"mint,omitempty"`
	Owner   string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *InitializedAccount) Reset() {
	*x = InitializedAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_hm_hm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializedAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializedAccount) ProtoMessage() {}

func (x *InitializedAccount) ProtoReflect() protoreflect.Message {
	mi := &file_test_hm_hm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializedAccount.ProtoReflect.Descriptor instead.
func (*InitializedAccount) Descriptor() ([]byte, []int) {
	return file_test_hm_hm_proto_rawDescGZIP(), []int{8}
}

func (x *InitializedAccount) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *InitializedAccount) GetMint() string {
	if x != nil {
		return x.Mint
	}
	return ""
}

func (x *InitializedAccount) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

var File_test_hm_hm_proto protoreflect.FileDescriptor

var file_test_hm_hm_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x68, 0x6d, 0x2f, 0x68, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x68, 0x6d, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x68, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xe0, 0x02,
	0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x68, 0x6d, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x6d, 0x61, 0x70, 0x5f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x68, 0x6d, 0x2e, 0x4d, 0x61, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x00,
	0x52, 0x09, 0x6d, 0x61, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x68, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x12, 0x25,
	0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x68, 0x6d, 0x2e, 0x4d, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05,
	0x6d, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x62, 0x75, 0x72, 0x6e, 0x73, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x68, 0x6d, 0x2e, 0x42,
	0x75, 0x72, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x62, 0x75, 0x72, 0x6e, 0x73, 0x12, 0x4e, 0x0a, 0x13,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x68, 0x6d, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x12, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x1a, 0xaa, 0xf8,
	0x25, 0x16, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x8a, 0x05, 0x09, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x22, 0x7a, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x0a, 0x08, 0x74, 0x72, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x72, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2b, 0x0a, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x68, 0x6d, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x3a, 0x23, 0xaa, 0xf8, 0x25, 0x1f, 0x0a, 0x0c, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x8a, 0x05, 0x0e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x65, 0x0a, 0x07,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x68, 0x6d, 0x2e,
	0x4d, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x68, 0x6d, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x3a, 0x0d, 0xaa, 0xf8, 0x25, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x21, 0x0a, 0x04, 0x62, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x68, 0x6d, 0x2e, 0x42, 0x75, 0x72, 0x6e, 0x52, 0x04, 0x62,
	0x75, 0x72, 0x6e, 0x3a, 0x10, 0xaa, 0xf8, 0x25, 0x0c, 0x0a, 0x0a, 0x6d, 0x61, 0x70, 0x5f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x22, 0x74, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x0e, 0xaa, 0xf8, 0x25,
	0x0a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0x58, 0x0a, 0x04, 0x4d,
	0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x0a, 0xaa, 0xf8, 0x25, 0x06, 0x0a,
	0x04, 0x6d, 0x69, 0x6e, 0x74, 0x22, 0x5c, 0x0a, 0x04, 0x42, 0x75, 0x72, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x0a, 0xaa, 0xf8, 0x25, 0x06, 0x0a, 0x04, 0x62,
	0x75, 0x72, 0x6e, 0x22, 0x73, 0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x3a, 0x19, 0xaa,
	0xf8, 0x25, 0x15, 0x0a, 0x13, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0xab, 0x01, 0x0a, 0x0b, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45,
	0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x52, 0x45, 0x47, 0x55, 0x4c, 0x41, 0x52, 0x5f, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x53, 0x50, 0x4c, 0x49, 0x54, 0x10, 0x03, 0x12,
	0x0e, 0x0a, 0x0a, 0x41, 0x49, 0x5f, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x10, 0x04, 0x12,
	0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x41, 0x4c, 0x10, 0x05,
	0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d,
	0x46, 0x4c, 0x45, 0x45, 0x54, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x10, 0x07, 0x12,
	0x10, 0x0a, 0x0c, 0x46, 0x4c, 0x45, 0x45, 0x54, 0x5f, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x10,
	0x08, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x41, 0x50, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x55, 0x4d, 0x50,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x09, 0x42, 0x5c, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x68, 0x6d, 0x42, 0x07, 0x48, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x68, 0x6d, 0xa2, 0x02, 0x03, 0x54, 0x48, 0x58, 0xaa,
	0x02, 0x07, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x6d, 0xca, 0x02, 0x07, 0x54, 0x65, 0x73, 0x74,
	0x5c, 0x48, 0x6d, 0xe2, 0x02, 0x13, 0x54, 0x65, 0x73, 0x74, 0x5c, 0x48, 0x6d, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x54, 0x65, 0x73, 0x74,
	0x3a, 0x3a, 0x48, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_hm_hm_proto_rawDescOnce sync.Once
	file_test_hm_hm_proto_rawDescData = file_test_hm_hm_proto_rawDesc
)

func file_test_hm_hm_proto_rawDescGZIP() []byte {
	file_test_hm_hm_proto_rawDescOnce.Do(func() {
		file_test_hm_hm_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_hm_hm_proto_rawDescData)
	})
	return file_test_hm_hm_proto_rawDescData
}

var file_test_hm_hm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_hm_hm_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_test_hm_hm_proto_goTypes = []interface{}{
	(PaymentType)(0),           // 0: test.hm.PaymentType
	(*ModuleOutput)(nil),       // 1: test.hm.ModuleOutput
	(*Entity)(nil),             // 2: test.hm.Entity
	(*Transaction)(nil),        // 3: test.hm.Transaction
	(*Payment)(nil),            // 4: test.hm.Payment
	(*MapCreate)(nil),          // 5: test.hm.MapCreate
	(*Transfer)(nil),           // 6: test.hm.Transfer
	(*Mint)(nil),               // 7: test.hm.Mint
	(*Burn)(nil),               // 8: test.hm.Burn
	(*InitializedAccount)(nil), // 9: test.hm.InitializedAccount
}
var file_test_hm_hm_proto_depIdxs = []int32{
	3,  // 0: test.hm.ModuleOutput.transactions:type_name -> test.hm.Transaction
	4,  // 1: test.hm.Entity.payment:type_name -> test.hm.Payment
	5,  // 2: test.hm.Entity.map_create:type_name -> test.hm.MapCreate
	6,  // 3: test.hm.Entity.transfers:type_name -> test.hm.Transfer
	7,  // 4: test.hm.Entity.mints:type_name -> test.hm.Mint
	8,  // 5: test.hm.Entity.burns:type_name -> test.hm.Burn
	9,  // 6: test.hm.Entity.initialized_account:type_name -> test.hm.InitializedAccount
	2,  // 7: test.hm.Transaction.entities:type_name -> test.hm.Entity
	7,  // 8: test.hm.Payment.mint:type_name -> test.hm.Mint
	0,  // 9: test.hm.Payment.type:type_name -> test.hm.PaymentType
	8,  // 10: test.hm.MapCreate.burn:type_name -> test.hm.Burn
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_test_hm_hm_proto_init() }
func file_test_hm_hm_proto_init() {
	if File_test_hm_hm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_hm_hm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_hm_hm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_hm_hm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_hm_hm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_hm_hm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_hm_hm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_hm_hm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_hm_hm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Burn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_hm_hm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializedAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_test_hm_hm_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Entity_Payment)(nil),
		(*Entity_MapCreate)(nil),
		(*Entity_Transfers)(nil),
		(*Entity_Mints)(nil),
		(*Entity_Burns)(nil),
		(*Entity_InitializedAccount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_hm_hm_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_hm_hm_proto_goTypes,
		DependencyIndexes: file_test_hm_hm_proto_depIdxs,
		EnumInfos:         file_test_hm_hm_proto_enumTypes,
		MessageInfos:      file_test_hm_hm_proto_msgTypes,
	}.Build()
	File_test_hm_hm_proto = out.File
	file_test_hm_hm_proto_rawDesc = nil
	file_test_hm_hm_proto_goTypes = nil
	file_test_hm_hm_proto_depIdxs = nil
}
