---
name: Build and Publish Docker Image

on:
  release:
    types:
      - published

jobs:
  build:
    uses: ICN-Protocol/github-common/.github/workflows/build-docker.yml@v0.4.2
    permissions:
      contents: read
      packages: write
    with:
      imageName: ${{ github.event.repository.name }}
      push: true
      file: ./Dockerfile
    secrets:
      token: ${{ secrets.GIT_TOKEN }}
      password: ${{ secrets.GITHUB_TOKEN }}